package com.greenbuds.crunchprep.setups;

public enum AccountStatus {
	ACTIVE,INACTIVE,FREE,PAID,SEEN,UNSEEN,ACCEPTED,REJECTED,CORRECT,INCORRECT,UNMARKED,MARKED,
	LOW,MEDIUM,HIGH,ENABLE,DISABLE,NOT_TAKEN,TAKEN,PENDING,COMPLETED,TYPO,BUG,DOUBT,FEEDBACK,
	VOTEUP,VOTEDOWN,SINGLE,MULTIPLE,FILLIN,YES,NO,GREMATH,GREVERBAL,PREMIUM;

}
